//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCOnline.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TLCOnline.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Appointment.
        /// </summary>
        public static string AddAppoint {
            get {
                return ResourceManager.GetString("AddAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        public static string AddCust {
            get {
                return ResourceManager.GetString("AddCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Laser.
        /// </summary>
        public static string AddLaser {
            get {
                return ResourceManager.GetString("AddLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Appointment.
        /// </summary>
        public static string AddNewAppoint {
            get {
                return ResourceManager.GetString("AddNewAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Appointment Failed.
        /// </summary>
        public static string AddNewAppointFailed {
            get {
                return ResourceManager.GetString("AddNewAppointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Customer.
        /// </summary>
        public static string AddNewCust {
            get {
                return ResourceManager.GetString("AddNewCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Customer Failed.
        /// </summary>
        public static string AddNewCustFailed {
            get {
                return ResourceManager.GetString("AddNewCustFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Laser.
        /// </summary>
        public static string AddNewLaser {
            get {
                return ResourceManager.GetString("AddNewLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Laser Failed.
        /// </summary>
        public static string AddNewLaserFailed {
            get {
                return ResourceManager.GetString("AddNewLaserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Staff.
        /// </summary>
        public static string AddNewStaff {
            get {
                return ResourceManager.GetString("AddNewStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Staff Failed.
        /// </summary>
        public static string AddNewStaffFailed {
            get {
                return ResourceManager.GetString("AddNewStaffFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Staff.
        /// </summary>
        public static string AddStaff {
            get {
                return ResourceManager.GetString("AddStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aesthetician.
        /// </summary>
        public static string Aesthetician {
            get {
                return ResourceManager.GetString("Aesthetician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This customer and staff combination is already booked for the selected date and time..
        /// </summary>
        public static string AppointAlreadyExistsForBothCustomerAndStaff {
            get {
                return ResourceManager.GetString("AppointAlreadyExistsForBothCustomerAndStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This customer already has an appointment at the selected date and time..
        /// </summary>
        public static string AppointAlreadyExistsForThatCust {
            get {
                return ResourceManager.GetString("AppointAlreadyExistsForThatCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This staff is already booked for another appointment at the selected date and time..
        /// </summary>
        public static string AppointAlreadyExistsForThatStaff {
            get {
                return ResourceManager.GetString("AppointAlreadyExistsForThatStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date.
        /// </summary>
        public static string AppointDate {
            get {
                return ResourceManager.GetString("AppointDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment already exists for the selected date and time..
        /// </summary>
        public static string AppointDateAlreadyExists {
            get {
                return ResourceManager.GetString("AppointDateAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment date cannot be on a weekend..
        /// </summary>
        public static string AppointDateCannotOnWeekend {
            get {
                return ResourceManager.GetString("AppointDateCannotOnWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment date must be at least one day in the future..
        /// </summary>
        public static string AppointDateMustBeAtLeast1DayInTheFuture {
            get {
                return ResourceManager.GetString("AppointDateMustBeAtLeast1DayInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have more than 3 appointments at the same date and time..
        /// </summary>
        public static string AppointExceeded3 {
            get {
                return ResourceManager.GetString("AppointExceeded3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Time.
        /// </summary>
        public static string AppointTime {
            get {
                return ResourceManager.GetString("AppointTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        public static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password should match password.
        /// </summary>
        public static string ConfirmPasswordShouldMatchPassword {
            get {
                return ResourceManager.GetString("ConfirmPasswordShouldMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Price (RM).
        /// </summary>
        public static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Email.
        /// </summary>
        public static string CustEmail {
            get {
                return ResourceManager.GetString("CustEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customer with this Email already exists..
        /// </summary>
        public static string CustEmailAlreadyExists {
            get {
                return ResourceManager.GetString("CustEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer MyKad.
        /// </summary>
        public static string CustMyKad {
            get {
                return ResourceManager.GetString("CustMyKad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customer with this MyKad or Email already exists..
        /// </summary>
        public static string CustMyKadOrEmailAlreadyExists {
            get {
                return ResourceManager.GetString("CustMyKadOrEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustName {
            get {
                return ResourceManager.GetString("CustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount (%).
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date cannot be in the future..
        /// </summary>
        public static string HireDateCannotInFuture {
            get {
                return ResourceManager.GetString("HireDateCannotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is inactive. Please contact administrator..
        /// </summary>
        public static string InactiveAccountPleaseContactAdmin {
            get {
                return ResourceManager.GetString("InactiveAccountPleaseContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email/password..
        /// </summary>
        public static string IncorrectEmailPassword {
            get {
                return ResourceManager.GetString("IncorrectEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Name.
        /// </summary>
        public static string LaserName {
            get {
                return ResourceManager.GetString("LaserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A laser with this name already exists..
        /// </summary>
        public static string LaserNameAlreadyExists {
            get {
                return ResourceManager.GetString("LaserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Price (RM).
        /// </summary>
        public static string LaserPrice {
            get {
                return ResourceManager.GetString("LaserPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasers.
        /// </summary>
        public static string Lasers {
            get {
                return ResourceManager.GetString("Lasers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Appointments.
        /// </summary>
        public static string ListOfAppoint {
            get {
                return ResourceManager.GetString("ListOfAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Customers.
        /// </summary>
        public static string ListOfCust {
            get {
                return ResourceManager.GetString("ListOfCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Lasers.
        /// </summary>
        public static string ListOfLaser {
            get {
                return ResourceManager.GetString("ListOfLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Staffs.
        /// </summary>
        public static string ListOfStaff {
            get {
                return ResourceManager.GetString("ListOfStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item? All related tables will be affected. This action cannot be undone..
        /// </summary>
        public static string MessageDelete {
            get {
                return ResourceManager.GetString("MessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyKad without (-).
        /// </summary>
        public static string MyKad {
            get {
                return ResourceManager.GetString("MyKad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Appointments by Status.
        /// </summary>
        public static string NoOfAppointByStatus {
            get {
                return ResourceManager.GetString("NoOfAppointByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Appointments by Laser Name.
        /// </summary>
        public static string NoOfAppointsByLaserName {
            get {
                return ResourceManager.GetString("NoOfAppointsByLaserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Customers by Gender.
        /// </summary>
        public static string NoOfCustByGender {
            get {
                return ResourceManager.GetString("NoOfCustByGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Price (RM).
        /// </summary>
        public static string NormalPrice {
            get {
                return ResourceManager.GetString("NormalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        public static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptionist.
        /// </summary>
        public static string Receptionist {
            get {
                return ResourceManager.GetString("Receptionist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Customer....
        /// </summary>
        public static string SelectCust {
            get {
                return ResourceManager.GetString("SelectCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Laser....
        /// </summary>
        public static string SelectLaser {
            get {
                return ResourceManager.GetString("SelectLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Position....
        /// </summary>
        public static string SelectPosition {
            get {
                return ResourceManager.GetString("SelectPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Staff....
        /// </summary>
        public static string SelectStaff {
            get {
                return ResourceManager.GetString("SelectStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status....
        /// </summary>
        public static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Time....
        /// </summary>
        public static string SelectTime {
            get {
                return ResourceManager.GetString("SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Email.
        /// </summary>
        public static string StaffEmail {
            get {
                return ResourceManager.GetString("StaffEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A staff with this Email already exists..
        /// </summary>
        public static string StaffEmailAlreadyExists {
            get {
                return ResourceManager.GetString("StaffEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        public static string StaffId {
            get {
                return ResourceManager.GetString("StaffId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A staff member with this ID or MyKad or email already exists..
        /// </summary>
        public static string StaffIdOrMyKadAlreadyExists {
            get {
                return ResourceManager.GetString("StaffIdOrMyKadAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff MyKad.
        /// </summary>
        public static string StaffMyKad {
            get {
                return ResourceManager.GetString("StaffMyKad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name.
        /// </summary>
        public static string StaffName {
            get {
                return ResourceManager.GetString("StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Phone No.
        /// </summary>
        public static string StaffPhoneNo {
            get {
                return ResourceManager.GetString("StaffPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Position.
        /// </summary>
        public static string StaffPosition {
            get {
                return ResourceManager.GetString("StaffPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffs.
        /// </summary>
        public static string Staffs {
            get {
                return ResourceManager.GetString("Staffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLCOnline.
        /// </summary>
        public static string TLCOnline {
            get {
                return ResourceManager.GetString("TLCOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLCOnlineDB.
        /// </summary>
        public static string TLCOnlineDB {
            get {
                return ResourceManager.GetString("TLCOnlineDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Appointments.
        /// </summary>
        public static string TotalAppoint {
            get {
                return ResourceManager.GetString("TotalAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Customers.
        /// </summary>
        public static string TotalCust {
            get {
                return ResourceManager.GetString("TotalCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Lasers.
        /// </summary>
        public static string TotalLaser {
            get {
                return ResourceManager.GetString("TotalLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Staffs.
        /// </summary>
        public static string TotalStaff {
            get {
                return ResourceManager.GetString("TotalStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Appointments.
        /// </summary>
        public static string UpcomingAppoint {
            get {
                return ResourceManager.GetString("UpcomingAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Appointment.
        /// </summary>
        public static string UpdateAppoint {
            get {
                return ResourceManager.GetString("UpdateAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Appointment Failed.
        /// </summary>
        public static string UpdateAppointFailed {
            get {
                return ResourceManager.GetString("UpdateAppointFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer.
        /// </summary>
        public static string UpdateCust {
            get {
                return ResourceManager.GetString("UpdateCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer Failed.
        /// </summary>
        public static string UpdateCustFailed {
            get {
                return ResourceManager.GetString("UpdateCustFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Laser.
        /// </summary>
        public static string UpdateLaser {
            get {
                return ResourceManager.GetString("UpdateLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Laser Failed.
        /// </summary>
        public static string UpdateLaserFailed {
            get {
                return ResourceManager.GetString("UpdateLaserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Staff.
        /// </summary>
        public static string UpdateStaff {
            get {
                return ResourceManager.GetString("UpdateStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Staff Failed.
        /// </summary>
        public static string UpdateStaffFailed {
            get {
                return ResourceManager.GetString("UpdateStaffFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Appointment.
        /// </summary>
        public static string ViewAppoint {
            get {
                return ResourceManager.GetString("ViewAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Customer.
        /// </summary>
        public static string ViewCust {
            get {
                return ResourceManager.GetString("ViewCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Laser.
        /// </summary>
        public static string ViewLaser {
            get {
                return ResourceManager.GetString("ViewLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Staff.
        /// </summary>
        public static string ViewStaff {
            get {
                return ResourceManager.GetString("ViewStaff", resourceCulture);
            }
        }
    }
}
